### ISSUE TITLE
Review code / documentation

### ISSUE THREAD

**Issue by judith-bourque** [clessn/article_riding-volatility#1]
# Suggestions
Documentation, replication etc:
- [x] Cite properly Qc125.com as data source in README for `generate_table3.R`
- [x] Move dataset variable description from the README into a codebook. Can be a separate .md file
- [ ] #4
- [x] Write repo description in GitHub
- [ ] #3

Style:
- [ ] #5
- [x] If there is a particular order you should run R scripts, can number them like `1_tidy_data.R`

Details:
- [x] Remove this line if not relevant anymore
https://github.com/clessn/article_riding-volatility/blob/c70a4795c48f3dbe450bf9963a8b9eac92842d2b/codes/figure4_fragilityVSvolatility.R#L41
- [x] Comment out this line OR move to README
https://github.com/clessn/article_riding-volatility/blob/c70a4795c48f3dbe450bf9963a8b9eac92842d2b/codes/generate_table3.R#L3

# Highlights
- Looked at the JOP dataverse and this repo is quite well organized compared to some of their content!
- Very easy to read and understand what's happening without running the scripts
- Files are well organised and documented

**Comment by judith-bourque** [comment]
If there's respondent data that can't be published, could produce random data with a seed.

Would have to validate if this would prevent reidentification when compared with the final results.

**Comment by judith-bourque** [comment]
@hubcad25 I finished the review. Love the initiative and good job!! C'est vraiment cool! 👏 

For the suggestions, feel free to only address what you think is relevant. You can convert an item from the checklist into an issue by hovering over it.

**Comment by hubcad25** [comment]
Merci beaucoup, très apprécié! :D I created issues with bigger tasks. I probably won't standardize all the variable and file names before submitting given that it is clear enough IMO, but will keep it in the to-do
